name: project_flutter_uaspemob
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  path_provider: ^2.0.11
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.3.0 
  flutter_rating_bar: ^4.0.0
  timeago: ^3.3.0
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
